### PR TITLE
Give LESS_ROOT priority over STATIC_ROOT when in DEBUG

### PR DESCRIPTION
**Pull request by fonfon**
Currently in DEBUG, django-less will prefer the files in STATIC_ROOT over the ones in LESS_ROOT (delivered by the finders).

I had a couple of outdated files in my STATIC_ROOT, which forced me to do collectstatic on every change to have the updated files there. This way I didn't even notice that django-less would take care of that automatically.

### CODE REVIEW

**Comment by andreyfedoseev** [comment]
> django-less will prefer the files in STATIC_ROOT over the ones in LESS_ROOT (delivered by the finders).

LESS_ROOT is the folder the compiled CSS files are written to. It's not the folder where you store your .less files. django-less always searches for .less files in STATIC_ROOT.

**Comment by fonfon** [comment]
Yes, django-less will search for .less files in STATIC_ROOT - also in DEBUG. If the file exists there it will use it, and not the possibly more recent one of the app-specific static folder (my_app/static/).

Compare it to how Django itself handles static files: in DEBUG it won't read a single file from your STATIC_ROOT folder but always deliver files from the app-specific static folder or STATICFILES_DIRS.

**Comment by aaroncaito** [comment]
+1 would like to see some extra control for debugging / development purposes
LESS_FORCE = Always re-compile less files on each request
LESS_ONCE = Only check for recompile after each server restart
LESS_DEBUG = Output any debugging messages to log
borrowed from https://github.com/emberfeather/less.js-middleware

**Comment by andreyfedoseev** [comment]
This package is not longer maintained. 

Please use [django-static-precompiler](https://github.com/andreyfedoseev/django-static-precompiler) and submit an issue there if necessary. Thanks.

**Pull request closed without merging**
